version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - SECRET_KEY=dev_secret_key
      - GOOGLE_CLIENT_ID=YOUR_GOOGLE_CLIENT_ID